spring:
  application:
    name: job-platform-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/job_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080